version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./app/cndt_router/assets/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  mysql_eastern:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: eastern
      MYSQL_USER: eastern
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./app/cndt_eastern_api/assets/init.sql:/docker-entrypoint-initdb.d/init.sql

  mysql_western:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: western
      MYSQL_USER: western
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - ./app/cndt_western_api/assets/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  memcached:
    image: memcached
    ports:
      - "11211:11211"

  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    ports:
      - 5080:5080
    volumes:
      - ./data:/data
    environment:
      - ZO_DATA_DIR=/data
      - ZO_ROOT_USER_EMAIL=root@example.com
      - ZO_ROOT_USER_PASSWORD=Complexpass#123