version: '3.8'

networks:
  default:
    name: cndt2023
    driver: bridge

services:

  go-server:
    image: auto-inst-go-server
    pid: "host"    
    volumes:
      - /proc:/host/proc    

  go-auto:
    depends_on:
      - go-server  
    image: otel/autoinstrumentation-go:add-custom-log
    privileged: true
    pid: "host"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
      - OTEL_GO_AUTO_TARGET_EXE=/app/main
      - OTEL_SERVICE_NAME=GO_SERVER_EBPF
      - OTEL_PROPAGATORS=tracecontext,baggage
      - OTEL_RESOURCE_ATTRIBUTES="THIS'S=ATTRIBUTE"
    volumes:
      - /proc:/host/proc

  python-client:
    image: auto-inst-python-client
    ports:
      - 8080:8080
    environment:
      - SERVER_URL_GO_SERVER=http://go-server:8080
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
    deploy:
      resources:
        limits:
          memory: 300M
    restart: unless-stopped      