apiVersion: v1
kind: Pod
metadata:
  name: app-for-k8soperator-nodejs-server-pod
  labels:
    app: app-for-k8soperator-nodejs-server-pod
  annotations: 
    instrumentation.opentelemetry.io/inject-nodejs: "true"
spec:
  containers:
  - name: app-for-k8soperator-nodejs-server
    image: ghcr.io/keisukesakasai/app_for_k8soperator_nodejs_server:latest
    ports:
    - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: app-for-k8soperator-nodejs-server-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: app-for-k8soperator-nodejs-server-pod